name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-16-16-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-16-16-yarn
      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Lint
        run: yarn lint
  build:
    name: Build on ${{matrix.os}} GraphQL ${{matrix.graphql_version_or_tag}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        graphql_version_or_tag: [experimental-stream-defer]
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-16-${{matrix.graphql_version_or_tag}}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-16-${{matrix.graphql_version_or_tag}}-yarn
      - name: Use GraphQL ${{matrix.graphql_version_or_tag}}
        run: node ./scripts/match-graphql.js ${{matrix.graphql_version_or_tag}}
      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Build
        run: yarn ts:transpile
  test:
    name: Test on ${{matrix.os}}, Node ${{matrix.node_version}} and GraphQL ${{matrix.graphql_version_or_tag}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node_version: [10, 16]
        graphql_version_or_tag: [experimental-stream-defer]
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node_version }}
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{matrix.node_version}}-${{matrix.graphql_version_or_tag}}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{matrix.node_version}}-${{matrix.graphql_version_or_tag}}-yarn
      - name: Use GraphQL ${{matrix.graphql_version_or_tag}}
        run: node ./scripts/match-graphql.js ${{matrix.graphql_version_or_tag}}
      - name: Install Dependencies using Yarn
        run: yarn install --ignore-engines && git checkout yarn.lock
      - name: Cache Jest
        uses: actions/cache@v2
        with:
          path: .cache/jest
          key: ${{ runner.os }}-${{matrix.node_version}}-${{matrix.graphql_version_or_tag}}-jest-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{matrix.node_version}}-${{matrix.graphql_version_or_tag}}-jest-
      - name: Test
        run: yarn test --ci
        env:
          CI: true
